### ISSUE TITLE
Small Issue

### ISSUE THREAD

**Issue by OvanLRU** [realmarble/moss-lancer#1]
Love what you have here, it looks fantastic, however I'm having a couple small issues.
I listed the objectives and deploys but they do not appear on the generated briefing. The second thing is it seems like only the encryption loading is working for me. Would love any input or a bit more detailed details on how to get these to work properly.

**Comment by realmarble** [comment]
Hi! The main thing usually causing issues is that some fields should be arrays, and field validation for specific types of data isn't implemented yet. I'd recommend checking out the example briefing [here](https://github.com/realmarble/moss-lancer/blob/main/briefing%2Fexamplebrief.json). Appreciate the praise a lot, thanks! docs are a huge work in progress though, since I mostly forget about it and work on new stuff for it.

**Comment by realmarble** [comment]
if no further support is needed, i see it's ab out time to close this.
