### ISSUE TITLE
Forge issue

### ISSUE THREAD

**Issue by S-Ulls** [realmarble/moss-lancer#2]
Hey there, pretty new to github so I have no idea if this is a good report.

I'm currently running Foundry via forge to be able to have multiple versions of Foundry at once. I am currently using Build 312. When attempting to save a brief or message as an assembly, I get an error message stating that "ReferenceError: Assignment to undeclared variable AssemblyStorageTemp 

I can't seem to find any methods to actually declare it. Any advice would be great

![](https://i.gyazo.com/a0750bf2cd6e9b5ea34e146815346383.png)

**Comment by realmarble** [comment]
Hi, thanks for reaching out. This is a known error that was fixed in [0.0.7](https://github.com/realmarble/moss-lancer/releases/tag/0.0.7). However, due to different handling of package installation between foundry and forge you may not have updated automatically. Try installing the new version from the manifest file and let me know if the error persists.

**Comment by S-Ulls** [comment]
Ah that sorted it. 

Strange issue but it seems to be considering 0.0.61 the latest. No idea what can be done with that but I figure its worth letting you know.

Thanks for the help mate, and have a good one

**Comment by realmarble** [comment]
The biggest problem is that as of right now 0.0.61 does not exist. It was deleted, being replaced by 0.0.7.
